version: '3.4'

services:
  rabbitmq3:
    container_name: "rabbitmq_container"
    image: rabbitmq:3.8-management-alpine
    environment:
     - RABBITMQ_DEFAULT_USER=myuser
     - RABBITMQ_DEFAULT_PASS=mypassworld
    ports:
        - '5672:5672'
        - '15672:15672'
  readapi:
    container_name: "readapi_container"
    image: ${DOCKER_REGISTRY-}readapi
    build:
      context: .
      dockerfile: src/ReadApi/Dockerfile
    ports:
     - "9000:443"
     - "9001:80"
    environment:
     - ASPNETCORE_ENVIRONMENT=Development
     - ASPNETCORE_URLS=https://+:443;http://+:80
     - RABBIT_USER=myuser
     - RABBIT_PASS=mypassworld
     - RABBIT_HOSTNAME=host.docker.internal
     - ConnectionStrings:DbConnection=User ID =postgres;Password=postgres;Server=pg_container;Port=5432;Database=test;Integrated Security=true;Pooling=true;
    restart: on-failure
    depends_on:
     - rabbitmq3

  #auditqueue: 
  #  container_name: "auditqueue_container"
  #  image: ${DOCKER_REGISTRY-}auditqueue
  #  build:
  #      context: .
  #      dockerfile: src/AuditQueue/Dockerfile
  #  environment:
  #   - ASPNETCORE_ENVIRONMENT=Development
  #   - ASPNETCORE_URLS=https://+:443;http://+:80
  #   - RABBIT_USER=myuser
  #   - RABBIT_PASS=mypassworld
  #   - RABBIT_HOSTNAME=host.docker.internal
  #   - ConnectionStrings:DbConnection=User ID =postgres;Password=postgres;Server=pg_container;Port=5432;Database=test;Integrated Security=true;Pooling=true;

  #  restart: on-failure
  #  depends_on:
  #   - db

  pgadmin: 
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
        PGADMIN_DEFAULT_EMAIL: admin@admin.com
        PGADMIN_DEFAULT_PASSWORD: root
    ports:
        - "5050:80"

  db:
    container_name: pg_container
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - db:/mount/nabin-ssd/docker/lib/postgresql/data
volumes:
  db:
    driver: local   